quarkus:
  devservices:
    enabled: false
  http:
    access-log:
      enabled: ${HTTP_LOGS_ENABLED:false}
    auth:
      permission:
        default:
          policy: ${AUTH_POLICY:authenticated}
          paths: /*
        swagger:
          policy: permit
          paths: /q/openapi,/documentation/*,/branding/*
        dev-ui:
          paths: /q/dev/*
          policy: permit
        test:
          paths: /test
          policy: permit
    cors:
      ~: true
      headers: accept,authorization,content-type,x-requested-with,Time-Zone
      methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      origins: '*'
  log:
    category:
      "io.quarkus.bootstrap":
        level: WARN
      "software.amazon.awssdk":
        level: WARN
      "software.amazon.awssdk.request":
        level: DEBUG
      "org.jboss.threads":
        level: WARN
    console:
      format: 'traceId: %X{X-Amzn-Trace-Id} | userEmail: %X{userEmail} [%-5p] %c{1}
        %C - %m%n'
    level: INFO
  swagger-ui:
    path: /documentation
    theme: outline
  oidc:
    enabled: true
    discovery-enabled: 'false'
    auth-server-url: ${AUTH_API_URL:authApiUrl}
    client-id: ${AUTH_API_CLIENT_ID:authApiClientId}
    jwks-path: .well-known/jwks.json
  vertx:
    warning-exception-time: '15'
  native:
    additional-build-args: --report-unsupported-elements-at-runtime, -H:ReflectionConfigurationFiles=reflection-config.json

'%dev':
  quarkus:
    http:
      auth:
        permission:
          default:
            policy: authenticated
            paths: /*
    oidc:
      enabled: 'true'

    rest-client:
      "auth0-token-api":
        uri: https://shekel-tracker.eu.auth0.com/oauth/token
        scope: javax.inject.Singleton
      "auth0-m2m-api":
        uri: https://shekel-tracker.eu.auth0.com/api/v2/users
        scope: javax.inject.Singleton

auth0:
  credentials:
    m2m:
      client-id: ${AUTH_M2M_CLIENT_ID:authM2mClientId}
      audience: ${AUTH_M2M_AUDIENCE:authM2mAudience}
      grand-type: ${AUTH_M2M_GRAND_TYPE:authM2mGrandType}
      client-secret: ${AUTH_M2M_CLIENT_SECRET:authM2mClientSecret}
